#!/usr/bin/env bash

###########
# Aliases #
###########

# Make
alias m='make'

# System update
alias system-update='yay -Syu --cleanafter --answerdiff=None --answeredit=None'

# Trash-CLI
# alias t='trash-put'

# Kill process using fuzzy selector
fkill () {
  ps aux | fzf | awk '{ print $2 }' | xargs kill
}

# ripgrep
# alias grep='rg'

# xsel
alias copy='xsel -ib'
alias paste='xsel -ob'

# eza
alias ls='eza'

# fd
# alias find='fd'

# Git fuzzy switch branches
fgc () {
  git checkout $(git branch | fzf)
}

# capture the output of a command so it can be retrieved with ret
alias cap='tee /tmp/capture.out;'
# return the output of the most recent command that was captured by cap
alias ret='cat /tmp/capture.out;'
